# SPDX-License-Identifier: MIT
# Copyright (C) 2021 Roland Csaszar
#
# Project:  Buildnis
# File:     commandline_arguments.py
# Date:     09.Mar.2021
###############################################################################

from __future__ import annotations

import logging
from typing import List

from buildnis.modules.config import DEFAULT_CONFIG_FILE, FilePath


class CommandlineArguments:
    """Holds information about the command line arguments passed to the program.

    Its attributes are the possible command line arguments of the program.

    Attributes:

        project_config_file (FilePath): the path to the project config file to
                                        use
        conf_dir (FilePath): the path to the directory to write generated
                                configurations to
        conf_scripts_dir (FilePath): the path to the directory to search for additional
                                    build tool configure scripts.
        log_file (FilePath): the path to the log file to write.
        log_level (int): the minimum log level
        do_configure (bool): run only  the configure phase of the build
        do_build (bool): run only the build phase of the build
        build_targets (List[str]): list of build targets that should be build
        do_install (bool): only run the install phase of the build
        install_targets (List[str]): the list of targets to install
        do_clean (bool): delete all files generated by the build phase
        do_distclean (bool): delete all generated files (build and configuration)
        do_check_what_to_do (bool): do everything that has not been done yet.
    """

    ############################################################################
    def __init__(self, src: object) -> None:
        """Initializes all attributes to a sane default value.

        Args:
            src (object): the object to use to fill the values of the command
                            line argument instance
        """
        self.initAttribs(src)

        self.do_check_what_to_do: bool = False

        self.checkTargetArgs(name="build_targets")

        self.checkTargetArgs(name="install_targets")

    ############################################################################
    def initAttribs(self, src: object) -> None:
        """Initializes all attributes to default values if not set from the
        command-line, that means, that attribute isn't an attribute of `src`.

        Args:
            src (object): The object holding the parsed command-line arguments.
        """
        try:
            self.project_config_file: FilePath = src.project_config_file
        except AttributeError:
            self.project_config_file: FilePath = DEFAULT_CONFIG_FILE
        try:
            self.conf_dir: FilePath = src.conf_dir
        except AttributeError:
            self.conf_dir: FilePath = ""
        try:
            self.conf_scripts_dir: FilePath = src.conf_scripts_dir
        except AttributeError:
            self.conf_scripts_dir: FilePath = ""
        try:
            self.log_file: FilePath = src.log_file
        except AttributeError:
            self.log_file: FilePath = ""
        try:
            self.log_level: int = src.log_level
        except AttributeError:
            self.log_level: int = logging.INFO
        try:
            self.do_configure: bool = src.do_configure
        except AttributeError:
            self.do_configure: bool = False
        try:
            self.do_build: bool = src.do_build
        except AttributeError:
            self.do_build: bool = False
        try:
            self.do_install: bool = src.do_install
        except AttributeError:
            self.do_install: bool = False
        try:
            self.do_clean: bool = src.do_clean
        except AttributeError:
            self.do_clean: bool = False
        try:
            self.do_distclean: bool = src.do_distclean
            if self.do_distclean is True:
                self.do_clean = True
        except AttributeError:
            self.do_distclean: bool = False
        try:
            self.build_targets: List(str) = src.build_targets
        except AttributeError:
            self.build_targets: List(str) = None
        try:
            self.install_targets: List(str) = src.install_targets
        except AttributeError:
            self.install_targets: List(str) = None

    ############################################################################
    def checkTargetArgs(self, name: str) -> None:
        """Checks the list stored in the attribute with the given name and
        flattens it to a single list if it contains another list.

        Args:
            name (str): the name of the attribute to check the stored list of
        """
        tmp_targets = []
        if getattr(self, name) is not None and getattr(self, name) != []:
            self.flattenList(name, tmp_targets)

    ############################################################################
    def flattenList(self, name: str, tmp_targets: List):
        """Flattens the given list to a single list.

        Args:
            name (str): The attribute's name, the list to flatten.
            tmp_targets (List): Where to sore the flattened list.
        """
        for target in getattr(self, name):
            if target != []:
                self.doAppendTarget(tmp_targets, target)
        setattr(self, name, tmp_targets)

    ############################################################################
    @staticmethod
    def doAppendTarget(tmp_targets: List, target: object) -> None:
        """Appends a target to the list of targets.

        Args:
            tmp_targets (List): the list of targets to append
            target (object): the target to check if it is a list or a single element.
        """
        if isinstance(target, List):
            for sub_target in target:
                tmp_targets.append(sub_target)
        else:
            tmp_targets.append(target)
